# Generated by Django 4.1.11 on 2023-10-10 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0004_wagtail42_images"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialmediasettings",
            name="default_sharing_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.customimage",
            ),
        ),
    ]
