# Generated by Django 3.2.12 on 2022-05-31 10:42

from django.db import migrations

import workshop.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="navigationsettings",
            name="footer_links",
            field=workshop.utils.fields.StreamField(
                blank=True, use_json_field=True
            ),
        ),
        migrations.AlterField(
            model_name="navigationsettings",
            name="footer_navigation",
            field=workshop.utils.fields.StreamField(
                blank=True, use_json_field=True
            ),
        ),
        migrations.AlterField(
            model_name="navigationsettings",
            name="primary_navigation",
            field=workshop.utils.fields.StreamField(
                blank=True, use_json_field=True
            ),
        ),
        migrations.AlterField(
            model_name="navigationsettings",
            name="secondary_navigation",
            field=workshop.utils.fields.StreamField(
                blank=True, use_json_field=True
            ),
        ),
    ]
